# RabbitMQ konfiguracija
app.rabbit.exchange=care-exchange
app.rabbit.queue=care-queue
app.rabbit.routing-key=care-routing-key

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

server.port=8082
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# PostgreSQL konekcija
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/OnlyBunsISA
spring.datasource.username=postgres
spring.datasource.password=super
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Prikaz SQL upita (opciono, za debug)
spring.jpa.show-sql=true
spring.application.name=OBCare
spring.profiles.active=dev
