spring.application.name=OnlyBuns
spring.profiles.active=dev

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/OnlyBunsISA
spring.datasource.username= postgres
spring.datasource.password= super
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.task.scheduling.pool.size=10

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=onlybunsisa5@gmail.com
spring.mail.password=jvmeyqfudndkmgrt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.web.cors.allowed-origin-patterns=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allow-credentials=true

# Eureka konfiguracija
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Omogućavanje retry politike za load balancer
spring.cloud.loadbalancer.retry.max-retries-on-next-service-instance=5
spring.cloud.loadbalancer.ribbon.enabled=true
spring.cloud.loadbalancer.retry.enabled=true
spring.cloud.loadbalancer.retry.max-attempts=6
spring.cloud.loadbalancer.retry.initial-interval=500
spring.cloud.loadbalancer.retry.max-interval=2000
spring.cloud.loadbalancer.retry.multiplier=1

# Aktivacija load balancer-a
spring.cloud.loadbalancer.enabled=true

# Za korišćenje round-robin algoritma (default je Round Robin)
spring.cloud.loadbalancer.client.default-ribbon-enabled=true

# Registracija instanci i konfiguracija balancer-a (ako je potrebno)
spring.cloud.loadbalancer.ribbon.listOfServers=localhost:8081,localhost:8082